name: flutter_godot_example
description: "Demonstrates how to use the flutter_godot plugin."
publish_to: "none"
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_godot:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
