name: flutter_godot
description: "The flutter_godot plugin can embed Godot games as Widget into Flutter applications and support two-way communication."
version: 0.0.3
repository: https://github.com/wyq0918dev/flutter_godot

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_plugin_android_lifecycle: ^2.0.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wyq0918dev.flutter_godot
        pluginClass: FlutterGodotPlugin
        dartPluginClass: FlutterGodot
      ios:
        dartPluginClass: FlutterGodotCompat
      linux:
        dartPluginClass: FlutterGodotCompat
      macos:
        dartPluginClass: FlutterGodotCompat
      windows:
        dartPluginClass: FlutterGodotCompat
      web:
        pluginClass: FlutterGodotWeb
        fileName: flutter_godot_web.dart

topics:
  - godot
  - game

screenshots:
  - description: example app screenshot
    path: screenshot.png
    type: "image/png"
