name: flutter_godot
description: "Embed a Godot game as a widget in a Flutter app."
version: 0.0.1
repository: https://github.com/wyq0918dev/flutter_godot

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_plugin_android_lifecycle: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wyq0918dev.flutter_godot
        pluginClass: FlutterGodotPlugin
        dartPluginClass: FlutterGodot
      ios:
        dartPluginClass: FlutterGodotCompat
      linux:
        dartPluginClass: FlutterGodotCompat
      macos:
        dartPluginClass: FlutterGodotCompat
      windows:
        dartPluginClass: FlutterGodotCompat
      web:
        pluginClass: FlutterGodotWeb
        fileName: flutter_godot_web.dart
